import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.scss'

import { Skranji, MedievalSharp, Pirata_One } from 'next/font/google'
import Navbar from '@/components/Navbar'

const skranji = Skranji({
  weight: ['400', '700'], // choose which weights you want
  subsets: ['latin'],
})
const medievalSharp = MedievalSharp({
  weight: ['400'], // choose which weights you want
  subsets: ['latin'],
})
const pirataOne = Pirata_One({
  weight: ['400'], // choose which weights you want
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${pirataOne.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
