import type { Metadata, Viewport } from 'next'
import './globals.scss'

import {
  Skranji,
  MedievalSharp,
  Pirata_One,
  Caesar_Dressing,
} from 'next/font/google'
import Navbar from '@/components/Navbar'

// const skranji = Skranji({
//   weight: ['400', '700'], // choose which weights you want
//   subsets: ['latin'],
// })
const medievalSharp = MedievalSharp({
  weight: ['400'], // choose which weights you want
  subsets: ['latin'],
})
// const pirataOne = Pirata_One({
//   weight: ['400'], // choose which weights you want
//   subsets: ['latin'],
// })
// const caesarDressing = Caesar_Dressing({
//   weight: ['400'], // choose which weights you want
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const viewport: Viewport = {
  themeColor: '#000000',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <meta name='theme-color' content='#39ff14' />
      </head>
      <body className={`${medievalSharp.className}`}>
        <Navbar />
        {children}
        <div className='background'></div>
      </body>
    </html>
  )
}
