import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.scss'

import { Skranji } from 'next/font/google'

const skranji = Skranji({
  weight: ['400', '700'], // choose which weights you want
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${skranji.className}`}>{children}</body>
    </html>
  )
}
